[package]
name = "rust-advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
once_cell = "1.20.2"
regex = "1.11.1"
structopt = "0.3.26"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmarks"
harness = false